## "i removed server.port and define it in configuration intellij to enable runnig multile instances for Load balancing ^_^ "
spring:
   datasource:
        url: jdbc:postgresql://localhost:5432/dxcsynergyidentity


