server:
   port: 8083
spring:
   datasource:
        url: jdbc:postgresql://localhost:5432/dxcsynergynotification
   kafka:
       consumer:
         bootstrap-servers: localhost:9092
         group-id: dxc-group
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                  auto-offset-reset: earliest
                  enable-auto-commit: false

         properties:
           spring.json.trusted.packages: "*"

